before_commands:
  - sudo pip3 install typing
  - sudo pip3 install antlr4-python3-runtime
  - sudo pip3 install httplib2
  - sudo pip3 install cleo==0.6.1
  - sudo pip3 install coverage

build:
    dependencies:
        before:
            - pip3 install typing
            - pip3 install antlr4-python3-runtime
            - pip3 install httplib2
            - pip3 install cleo==0.6.1
            - pip3 install coverage
    tests:
        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - test/*
        - sdoc/antlr/*

tools:
    pylint:
        python_version: '3'
        config_file: pylintrc
