language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'

sudo: true

install:
  - cd $HOME
  - pip3 install antlr4-python3-runtime
  - pip3 install httplib2
  - pip3 install cleo==0.6.1

script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest discover -s test -p *Test.py
